### PR TITLE
Fix inaccurate ETAs

### PR DESCRIPTION
**Pull request by lemonsqueeze**
Hi,

This is the pull request for issue #28.

I saw there were changes since last time i took a look at pv, and it seems ETAs are still inaccurate so i took the opportunity to revisit and clean up my patch and rebase it on latest main branch. Documentation should be up to date too now.

`--eta-window` allows to set the time window for average rate computation (default 30s)

**Quick test**
    
in one shell:

    $ dd if=/dev/zero of=/tmp/foo bs=1M count=5                 # simulate fast initial rate,
    $ (while true; do ls /*; sleep 1; done) >> /tmp/foo         # then slow rate. leave running ...
    
in another shell:

    $ tail -f -n +1 /tmp/foo | pv -s 800M > /dev/null
    
    5.62MiB 0:00:17 [33.1KiB/s] [>                              ]  0% ETA 0:40:02
            bad:  (pv 1.6.6 - 1.6.20)
            ETA of a few minutes that keeps increasing ever and ever ...
    
    5.62MiB 0:00:16 [33.1KiB/s] [>                              ]  0% ETA 6:45:53
            good:
            ETA of 6+ hours, which is how long it'll take to reach 800Mb at 33k/s

### CODE REVIEW

**Comment by a-j-wood** [comment]
Thanks for this - I have merged it in, and will make some additional small changes.  It will be in the next release after 1.6.20.

**Comment by a-j-wood** [comment]
One question - can you elaborate on what this means, in `update_history_avg_rate()` in `src/pv/display.c`?

        if (!(last_elapsed == 0.0 ||        /* Empty */
              elapsed_sec > last_elapsed + state->history_interval))
                return;


The comment is a little unclear and the logic is not immediately obvious.

I assume it returns without action, if either the previous history time was at elapsed time 0.0 (i.e. no time has passed yet), or if insufficient time has passed since the last check for us to need to do anything yet.  Have I interpreted that correctly?

**Comment by lemonsqueeze** [comment]
> Thanks for this - I have merged it in, and will make some additional small changes. It will be in the next release after 1.6.20.

Cool, good luck with next release !

**Comment by lemonsqueeze** [comment]
> One question - can you elaborate on what this means, in `update_history_avg_rate()` in `src/pv/display.c`?
> 
> ```
>     if (!(last_elapsed == 0.0 ||        /* Empty */
>           elapsed_sec > last_elapsed + state->history_interval))
>             return;
> ```
> 
> The comment is a little unclear and the logic is not immediately obvious.
> 
> I assume it returns without action, if either the previous history time was at elapsed time 0.0 (i.e. no time has passed yet), or if insufficient time has passed since the last check for us to need to do anything yet. Have I interpreted that correctly?

Yes basically that's it. I agree, it's not very clear the way it's written.
Should have written it with the not factored inside :

```
    if (last_elapsed &&      /* History not empty */ 
        elapsed_sec < last_elapsed + state->history_interval)
            return;
```

So return if not enough time has passed for an update (and it's not the first call where history is empty).

**Comment by a-j-wood** [comment]
Thanks.  I had definitely misunderstood it.

How about this:

     state->history_last = last = (last + 1) % len;

What is the intended state of `status->history_last` and `last`, after that statement?  I don't generally like statements of the form "foo = bar = baz" because I find them difficult to follow, so I'd prefer to break it out into separate statements.

**Comment by lemonsqueeze** [comment]
> Thanks. I had definitely misunderstood it.
> 
> How about this:
> 
> ```
>  state->history_last = last = (last + 1) % len;
> ```
> 
> What is the intended state of `status->history_last` and `last`, after that statement? I don't generally like statements of the form "foo = bar = baz" because I find them difficult to follow, so I'd prefer to break it out into separate statements.

They should always be equal. Same as doing:
```
state->history_last = (last + 1) % len;
last = state->history_last;
```


`state->history_last` is the index of the last entry in the circular buffer. I'm aliasing it as `last` because it's more concise : now we can write `state->history[last]` instead of `state->history[state->history_last]`. I guess the confusing part is that now i have to change it in two places when it must be changed.

I'm not a big fan of macros usually, but maybe this would be cleaner here:
Just define `last` as a macro instead of variable in this function, this way there is no aliasing.  
Same for first:

```C
static void update_history_avg_rate(pvstate_t state, long long total_bytes,
                                    long double elapsed_sec, long double rate)
{
#define first   state->history_first
#define last    state->history_last
        long double last_elapsed = state->history[last].elapsed_sec;

        if (!(last_elapsed == 0.0 ||  /* Empty */
              elapsed_sec > last_elapsed + state->history_interval))
                return;

        if (last_elapsed) { /* Not empty, add new entry in circular buffer */
                int len = state->history_len;
                state->history_last = (last + 1) % len;
                if (last == first)
                        state->history_first = (first + 1) % len;
        }

        state->history[last].elapsed_sec = elapsed_sec;
        state->history[last].total_bytes = total_bytes;

        if (first == last)
                state->current_avg_rate = rate;
        else {
                long long bytes = (state->history[last].total_bytes -
                                   state->history[first].total_bytes);
                long double sec = (state->history[last].elapsed_sec -
                                   state->history[first].elapsed_sec);
                state->current_avg_rate = bytes / sec;
        }
#undef first
#undef last
}
```

**Comment by lemonsqueeze** [comment]
Btw just in case you're not super familiar with the github pull-request process, usually what happens is that you can ask for changes, clarification etc from the submitter, who then makes the requested changes (ammends his pull-request) and you only click `merge` at the very end when everything is 100% good from your point of view. This way you don't have to add more commits later. I guess it happened the other way round here, but that works too =)

**Comment by a-j-wood** [comment]
Thanks for the clarification.

In this case I have been merging in several different things at once, and after applying your alterations a few things broke, so I've been committing bits and pieces and haven't really taken all of your changes in one go.

It's in a stable place now, I just wanted to make sure I understand what remains.

**Comment by lemonsqueeze** [comment]
I see what you mean, merging branches can be a nightmare sometimes.

**Pull request merged**
